# Generated by Django 4.1.6 on 2023-02-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
